### ISSUE TITLE
MessageEncoder probably leaks memory when there are errors during encoding.

### ISSUE THREAD

**Issue by erikcorry** [toitlang/toit#1104]
The destructor needs to clean up, and there needs to be a dont_free() method for use when its allocations have been handed over to the system (put in the Message).

**Comment by kasperl** [comment]
Did this get worse recently, @erikcorry?

**Comment by kasperl** [comment]
We believe this is solved by 2c60b5b2e47c33ba2eaea62ffb7e589300920497.
