### ISSUE TITLE
Support networking in build for Windows

### ISSUE THREAD

**Issue by kasperl** [toitlang/toit#133]
We're missing the networking primitives on Windows.

The similar code for BSD / POSIX targets is:
https://github.com/toitlang/toit/blob/master/src/resources/dns_posix.cc
https://github.com/toitlang/toit/blob/master/src/resources/tcp_bsd.cc
https://github.com/toitlang/toit/blob/master/src/resources/udp_bsd.cc

**Comment by mikkeldamsgaard** [comment]
@kasperl Should this be closed now?

**Comment by kasperl** [comment]
Fixed by @mikkeldamsgaard!
