### ISSUE TITLE
Missing python3-pip dependency for ESP-IDF install

### ISSUE THREAD

**Issue by joedeveloper** [toitlang/toit#140]
This step failed for me the first time running:

On Linux:

    $IDF_PATH/install.sh

Fixed with

     sudo apt install python3-pip

and running 

     $IDF_PATH/install.sh
again.

**Comment by dsobotta** [comment]
this should cover all dependencies that you need for compiling toit and esp-idf:  https://github.com/toitlang/toit/blob/master/README_OTHERPLATFORMS.md#2-install-dependencies

**Comment by floitsch** [comment]
The README now (actually already for a while) has instructions to run `install.sh`.
If you see other issues during building (especially Windows) please let us know.
