### ISSUE TITLE
Abnormal syntax highlighting with 4 space indentation

### ISSUE THREAD

**Issue by JUNGHUNKIM-7** [toitlang/toit#1596]
![toit](https://user-images.githubusercontent.com/67856304/235364806-f78527e6-a0e1-43de-b3cd-b7db37b2467d.PNG)

1. Problem
```
- Syntax highlighting consistency looks abnormal.
```
2. Env
```
Version: 1.78.0-insider (user setup)
Commit: 2c51b3de329d48f45eabe80316f099f46fd3a5cc
Date: 2023-04-26T05:19:40.699Z
Electron: 22.4.8
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Windows_NT x64 10.0.19045
Sandboxed: Yes
```

**Comment by kasperl** [comment]
Hi @JUNGHUNKIM-7. Thank you for the bug report. I think the issue might be related to the four space indentation style you're using here. Try using the recommended 2 space indentation and see if that helps.

https://docs.toit.io/language/style

**Comment by kasperl** [comment]
The problem is that the syntax highlighter recognizes certain patterns based on their indentation (2 or 4 spaces). It would be great to fix this.

Here is an example:

https://github.com/toitware/ide-tools/blob/dbda69afa5a6fa1a5cccf50527da7bb680b9e861/vscode/syntaxes/toit.tmLanguage.yaml#L129

**Comment by JUNGHUNKIM-7** [comment]
@kasperl 
Thank you for very detailed feedback! 
I should have checked the document carefully & never expected 2 space is official for such a very concised lang. if it has supported formatter in vscode, i could recognize it earlier.

Nice Project.
