### ISSUE TITLE
Add write method to BLE RemoteCharacteristic

### ISSUE THREAD

**Issue by matthezJ** [toitlang/toit#160]
A method for writting to a BLE RemoteCharacteristic would be great.

**Comment by kasperl** [comment]
Do you know if this would be easy to add, @mikkeldamsgaard?

**Comment by floitsch** [comment]
The latest version (at least the open-source one) now has a way to write to a RemoteCharacteristic:
https://github.com/toitlang/toit/blob/master/lib/ble.toit#L241
