### ISSUE TITLE
Does the ESP-IDF NVS implementation still use throwing new?

### ISSUE THREAD

**Issue by lask** [toitlang/toit#179]
Previous versions of ESP-IDF had a throwing `new` which meant that it would crash the system close to garbage collection. The version of ESP-IDF we depend on today had a large rewrite of NVS, so the problem may be solved. We do, however, not know this and should investigate this.

**Comment by floitsch** [comment]
From what I could see, this has been fixed upstream.

**Comment by kasperl** [comment]
Marking as closed.
