### ISSUE TITLE
Support for DAC

### ISSUE THREAD

**Issue by krzychb** [toitlang/toit#204]
I could not find the API for [DAC](https://docs.espressif.com/projects/esp-idf/en/latest/esp32/api-reference/peripherals/dac.html#).
Is it implemented?
If not, do you plan to add it?
If doing so could you add support for [CW](https://docs.espressif.com/projects/esp-idf/en/latest/esp32/api-reference/peripherals/dac.html#_CPPv423dac_cw_generator_enablev)?

**Comment by floitsch** [comment]
Work has started: https://github.com/toitlang/toit/pull/893

**Comment by kasperl** [comment]
Is this fixed, @floitsch?

**Comment by floitsch** [comment]
Yes.
DAC is fully supported.
