### ISSUE TITLE
Prefix increment has NOT been removed?

### ISSUE THREAD

**Issue by igouy** [toitlang/toit#2172]
v2.0.0-alpha.143

```
main args:
  i := 10
  --i
```

> Toit does not have the prefix forms of ++ and --

So as expected 

```
$ toit.run try.toit
try.toit:4:3: error: Prefix decrement has been removed
  --i
  ^~~
```

but

```
main args:
  i := 10
  ++i  
  print i
```

```
$ toit.run try.toit
11
```

**Comment by floitsch** [comment]
It's an inconsistency...
We removed `--i` because it clashes with named arguments: `foo --named` or `foo --named=499`.
We could have removed `++i` at the same time, but it doesn't really hurt anyone. I'm open for removing it and making the language more consistent.

**Comment by igouy** [comment]
It doesn't really hurt anyone.
