### ISSUE TITLE
API docs don't show default values of parameters

### ISSUE THREAD

**Issue by snej** [toitlang/toit#2436]
toitdoc doesn’t show the default values of parameters. This can make it unclear how a method behaves. For example, from [`Deque.sort`](https://libs.toit.io/#sort(3%2C0%2C0%2Cin-place)):

> [sort](https://libs.toit.io/#sort(4%2C1%2C0%2Cin-place)) --in-place/[bool](https://libs.toit.io/core/objects/class-bool)= from/[int](https://libs.toit.io/core/numbers/class-int)= to/[int](https://libs.toit.io/core/numbers/class-int)= [compare] -> [List](https://libs.toit.io/core/collections/class-List)
> inherited
>Sorts the range [from..to[ using the given compare block. The sort is stable, meaning that equal elements do not change their relative order.
>Returns a new list if in-place is false. Returns this instance otherwise.

It’s unclear whether the default is an in-place copy. I assumed it was since, I reasoned, omitting `in-place=` wasn’t the same as setting it to false. Unfortunately I was wrong, causing a bug in my code that took an hour to track down.

It would have been clearer if the displayed signature had been

> sort --in-place/bool=false ...

**Comment by floitsch** [comment]
I happen to work on the toitdoc generator and viewer right now. I will try to get this (finally) improved.

I think I won't have the time to make the default-values "analyzed" (being able to click on methods...), but at least we should show the original code.
