### ISSUE TITLE
Use-before-assign analysis does not understand blocks

### ISSUE THREAD

**Issue by erikcorry** [toitlang/toit#245]
```
main:
  x := ?

  block := : x

  x = 0

  block.call
```
This warns about x not being initialized before use.

This analysis is not very accurate since x cannot be used before the block is called.

**Comment by floitsch** [comment]
Agreed.
We could track this as well, but it would things even more complicated. I doubt we will add this feature soon.

**Comment by floitsch** [comment]
I don't think I will find the time to implement this anytime soon.
Instead of keeping it around without any hope I'm closing it.
