### ISSUE TITLE
assert: how-to ?

### ISSUE THREAD

**Issue by igouy** [toitlang/toit#2493]
```
richards.toit

  assert: scheduler.queue-count == EXPECTED-QUEUE-COUNT
  assert: scheduler.hold-count == EXPECTED-HOLD-COUNT
```

I haven't been able to figure-out how to trigger the assert or where to see what happened.

**Comment by floitsch** [comment]
It's currently a bit difficult to enable asserts.
You need to run the compiler by hand with `-Xenable-asserts`. That's clearly not user-friendly.

I will prioritize making this easier. Probably `-O0` will have it on by default.

**Comment by floitsch** [comment]
I just uploaded a PR that makes `-O0` and `-O1` (the default) enable asserts.
There is also a flag to set enable-assert explicitly. We will expose it in Jaguar once a new SDK with this change has been released.

**Comment by igouy** [comment]
> You need to run the compiler by hand with `-Xenable-asserts`. That's clearly not user-friendly.

I can do that !

Is there a way for me to discover the available compiler flags?

**Comment by floitsch** [comment]
> > You need to run the compiler by hand with `-Xenable-asserts`. That's clearly not user-friendly.
> 
> I can do that !
> 
> Is there a way for me to discover the available compiler flags?

These compiler flags are mostly for testing and internal use, but you can find them here:
https://github.com/toitlang/toit/blob/master/src/flags.h#L45
