### ISSUE TITLE
Driver for touch screen on M5Stack Core2

### ISSUE THREAD

**Issue by kasperl** [toitlang/toit#25]
Porting existing drivers to Toit is a great place to start contributing to the Toit community. The M5Stack Core2 is a fantastic device. It comes with MIT licensed support for the touch support for the screen, but that support isn't yet available for Toit users:

https://github.com/m5stack/M5Core2/blob/master/src/M5Touch.h

It appears to be based on the FocalTech FT6336 chip and it uses I2C to communicate. It would be great to have a Toit package that makes the functionality available to all Toit users.

Here is the [source code of another driver package](https://github.com/imliubo/mpu6886-toit) that is useful on the M5Core and here is brief explanation on [how to start writing an I2C driver in Toit](https://github.com/toitlang/toit/discussions/22).

Happy hacking!

**Comment by kasperl** [comment]
Mentioned your work on the MPU6886 here, @imliubo. Thanks again!

**Comment by imliubo** [comment]
Thanks,has anyone start for touch upport? Maybe I can try it later, but I'm still stuck in other work...

**Comment by kasperl** [comment]
Not to my knowledge!

**Comment by imliubo** [comment]
A very simple driver for FT63xx capacitive touch chip.
[Link](https://github.com/imliubo/ft63xx-toit)

**Comment by kasperl** [comment]
Fixed by @imliubo here: https://pkg.toit.io/package/github.com%2Fimliubo%2Fft63xx-toit.

Fantastic work!
