### ISSUE TITLE
gpio_esp32 casts to ADCState without checks

### ISSUE THREAD

**Issue by floitsch** [toitlang/toit#306]
In line 125 of `src/resources/adc_esp32.cc` the code casts from a given byte-array to an `ADCState` without checking whether the object is in fact an `ADCState`.

**Comment by erikcorry** [comment]
To fix this ADCState should inherit from SimpleResource.  See the way the Sha1 class works. Basically a 'git grep Sha1' shows you the places that need fixing so that you can just declare the type in the ARGS macro of the primitive.  Also ADCState should be called AdcState since we don't capitalize abbreviations in our code.

**Comment by un01s** [comment]
I have browsed through the code about Sha1, crypto, SimpleResource, and ADCState. Pieced some code together. Before the PR, here are questions: For ARGS macro of the primitive, what argument can be passed there? Any rules? Can I pass AdcState as one of the arguments? How is the primitives of the modules compared with the methods of the classes? Thanks.

**Comment by erikcorry** [comment]
You can pass any type where primitive.h has is a macro named _A_T_Mytype.  So once you have added the _A_T_ADCState you can pass it as an argument.  Or rather _A_T_AdcState since abbreviations are only capitalized on the first letter.

**Comment by erikcorry** [comment]
You can see how the _A_T_Sha1 macro is defined as an example.
It requires that there is a tag for AdcState, which is defined with a line in tags.h and TAG(AdcState) in the AdcState struct.

**Comment by kasperl** [comment]
Did the fix land, @un01s and @erikcorry?

**Comment by floitsch** [comment]
yes. This has been resolved.
