### ISSUE TITLE
Build issue using grep (BSD grep, GNU compatible) 2.6.0-FreeBSD

### ISSUE THREAD

**Issue by kasperl** [toitlang/toit#34]
Using grep (BSD grep, GNU compatible) 2.6.0-FreeBSD on macOS to build the tools:

``` sh
make tools    
```

leads to:

```
grep: unrecognized option `--perl-regexp'
usage: grep [-abcdDEFGHhIiJLlMmnOopqRSsUVvwXxZz] [-A num] [-B num] [-C[num]]
	[-e pattern] [-f file] [--binary-files=value] [--color=when]
	[--context[=num]] [--directories=action] [--label] [--line-buffered]
	[--null] [pattern] [file ...]
(standard_in) 1: parse error
```

**Comment by mikini** [comment]
Bugger, sorry for breaking the build :-|.

Suspected some platforms could potentially have an issue with this [when explicitly noting](https://github.com/toitlang/toit/pull/21#issue-1063051130) the use of [lookaround (PCRE feature)](https://www.pcre.org/original/doc/html/pcresyntax.html#SEC19)  and possible GNU grep specific command line option in commitlog, but expected the PR/review to reveal the project's stance on platform conformance.

It seems that on macOS [BSD grep replaced GNU grep in 10.8](https://stackoverflow.com/questions/16658333/grep-p-no-longer-works-how-can-i-rewrite-my-searches) and that it only supports BRE and ERE (and [is ancient and slow](https://news.ycombinator.com/item?id=19522456)). Can't find information about the exact package and source code in use at all, though (something [here](https://opensource.apple.com/source/text_cmds/text_cmds-99/grep/) but looks almost too dated).

The reg-ex is written to be rather explicit about the format, I guess a less aggressive reg-ex could do it. Or maybe just ditch reg-ex and use plain POSIX tools [cut](https://pubs.opengroup.org/onlinepubs/9699919799/utilities/cut.html) and [tail](https://pubs.opengroup.org/onlinepubs/9699919799/utilities/tail.html) would be a better option;
```
$ go version
go version go1.13.8 linux/amd64
$ go version|cut -d" " -f 3| tail -c+3
1.13.8
```
