### ISSUE TITLE
WARNING: unhandled system message 2 Array of size 3

### ISSUE THREAD

**Issue by snxx-lppxx** [toitlang/toit#465]
```sh
$ toit run --no-device main.toit
WARNING: unhandled system message 2 Array of size 3
_
```

**Comment by snxx-lppxx** [comment]
Hello @kasperl, nothing happens after this message. The underscore character describes the state of the problem.

**Comment by kasperl** [comment]
We believe we have fixed this by now. Let me know if you still encounter issues, @snxx-lppxx!
