### ISSUE TITLE
Couldn't find 'main' (with 0 or 1 argument)

### ISSUE THREAD

**Issue by snxx-lppxx** [toitlang/toit#673]
<details open="open">
<summary>Сode example:</summary>

```toit
main x/int y/string:
  x = 10
  y = "string"
  print x
  print y
```

</details>

---

```sh
$ toit run --no-device main.toit
# Couldn't find 'main' (with 0 or 1 argument)
# Compilation failed.
```

**Comment by floitsch** [comment]
A Toit program can only have a `main` function with 0 or 1 arguments.
If it has 1 argument, then the 1st argument is the list of parameters that was provided to it on the command-line. At least, that's the case for Toit programs that are written for the Desktop:

```
ᐅ cat ~/tmp/args.toit
main args:
  args.do: print it
ᐅ sdk/bin/toit.run ~/tmp/args.toit 1 2
1
2
```
