### ISSUE TITLE
Constructor named parameter gets shadowed by named setter for class variable

### ISSUE THREAD

**Issue by MikAtCosesy** [toitlang/toit#867]
The following code does not correctly set the bytes in the underlying ByteArray structure because the setter 'target' overshadows the named parameter 'target'. This happens without a warning and is hard to debug.

```
class RfData:
    data/ByteArray := ?
    constructor .data/ByteArray:

    constructor 
        --status/top.status
        --target/ByteArray:
        data = ByteArray 4

        //print "rfdata.target: $Target"

        net_type = status.net.type
        net_strength = status.net.strength
        ring_level = status.ring_level
        target = target
    ....

    target -> ByteArray:
        return data[1..]
    
    target= target/ByteArray:
        data.replace 1 target 0 3      //data[1..4] = target[0..3]
```

This is probably hard to erase, but it would be nice with a warning.

**Comment by floitsch** [comment]
If I understand correctly, this is actually the opposite problem: the local parameter `target` shadows the setter `target` and assigning to it doesn't give any warning.

I think I will introduce a warning when a variable is assigned to itself.
Would that solve this issue?

**Comment by MikAtCosesy** [comment]
Aaah I see - I could not determine which of them were being overshadowed, but the result is the same either way. 

Yes I think it would help with a warning as that would make it much easier to find the error if it happens again.
