### ISSUE TITLE
WiFi can't find ssid after initial failure

### ISSUE THREAD

**Issue by floitsch** [toitlang/toit#871]
I just ran Jaguar on the ESP32 with the wrong SSID name.
Instead of reflashing, I changed the WiFi hotspot name. Despite multiple attempts the device did not manage to connect to it.
I keep getting the following error message:
```
[wifi] DEBUG: connecting
[wifi] WARN: connect failed {reason: access point not found}
[wifi] DEBUG: closing
```

After rebooting the device it can connect.

**Comment by kasperl** [comment]
We believe this was fixed in #910.
